### ISSUE TITLE
fix(내 편지 저장소페이지): UI 수정

### ISSUE THREAD

**Issue by codefug** [reindeer-letter/client#24]
# 🐛 fix

## 어떤 작업을 하나요?
- 내 편지 저장소 페이지를 시안에 맞게 수정합니다.
- 공동 컴포넌트 UI를 시안에 맞게 수정합니다.
- 손글씨 폰트를 교체합니다.

**Comment by anhyeryeon2** [comment]
앗 공통 컴포넌트 버튼 수정했는데 올린 pr 한번 확인해주시고 , 제외하고 하셔도 될 것 같습니다 !
